#! /usr/bin/env python
from linked_list import LinkedList

linked_list = LinkedList(1)
linked_list.add(2)
linked_list.add(3)
linked_list.add(2)
linked_list.add(2)
linked_list.add(2)
linked_list.add(3)
linked_list.add(5)
linked_list.add(3)
linked_list.add(2)
linked_list.add(6)
linked_list.add(2)
print(linked_list.printer())
linked_list.remove(2, 'all')
print(linked_list.printer())
linked_list.remove(3, 'all')
print(linked_list.printer())
linked_list.remove(1, 'index')
print(linked_list.printer())